### ISSUE TITLE
[bug] - Zigbuilds fails - when static linking pkg-config

### ISSUE THREAD

**Issue by dinbtechit** [rust-cross/cargo-zigbuild#89]
# Description
`cargo build  --target aarch64-unknown-linux-gnu -r` works fine  ✅
but 
`cargo zigbuild --target aarch64-unknown-linux-gnu -r` ❌

# Steps to reproduce
**Command**
```
rustup target add aarch64-unknown-linux-gnu
cargo zigbuild --target aarch64-unknown-linux-gnu -r
```
**Error**
```
The following warnings were emitted during compilation:

warning: In file included from build/expando.c:1:
warning: In file included from /usr/include/openssl/opensslv.h:109:
warning: /usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
warning: #include <openssl/opensslconf.h>
warning:          ^~~~~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.80`

Caused by:
  process didn't exit successfully: `/app/target/release/build/openssl-sys-bc542764a529c6f7/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR = /usr/lib/aarch64-linux-gnu
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR = /usr/include
  cargo:rustc-link-search=native=/usr/lib/aarch64-linux-gnu
  cargo:include=/usr/include
  cargo:rerun-if-changed=build/expando.c
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-unknown-linux-gnu")
  HOST = Some("aarch64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
  CC_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
  CC_aarch64_unknown_linux_gnu = Some("/root/.cache/cargo-zigbuild/0.16.0/zigcc-aarch64-unknown-linux-gnu.sh")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
  CFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
  CFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "/root/.cache/cargo-zigbuild/0.16.0/zigcc-aarch64-unknown-linux-gnu.sh" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/usr/include" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=In file included from build/expando.c:1:
  cargo:warning=In file included from /usr/include/openssl/opensslv.h:109:
  cargo:warning=/usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
  cargo:warning=#include <openssl/opensslconf.h>
  cargo:warning=         ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"/root/.cache/cargo-zigbuild/0.16.0/zigcc-aarch64-unknown-linux-gnu.sh\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"zigcc-aarch64-unknown-linux-gnu.sh\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel
      # On Alpine Linux
      apk add openssl-dev

  See rust-openssl documentation for more information:

      https://docs.rs/openssl
  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/main.rs:185:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
     2: build_script_main::validate_headers
     3: build_script_main::postprocess
     4: build_script_main::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

```

**Comment by NobodyXu** [comment]
It seems like zigbuild cannot use the openssl since it's cross compiling, which makes sense for me.

You need to turn out the "vendored" feature of openssl so that it would build openssl instead of using system-wide dep.

**Comment by dinbtechit** [comment]
That makes sense that it cannot use the system-wide deps.

For `cargo builds`, I have to specify the OpenSSL path (as shown below). 

```sh
export OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
export OPENSSL_INCLUDE_DIR=/usr/include
```

Is there a way I can specify the paths manually for `cargo zigbuilds`?  My project depends on openssl, libzmq and libsodium. libzmq and libsodium dont have the option to enable vendored feature. So I would really like to manually provide the linking path.

**Comment by NobodyXu** [comment]
For zmq, I checked libzmq-sys and zmq-sts, both will vendor zmq if it cannot find it on the system.

**Comment by messense** [comment]
Thanks for the help! @NobodyXu

**Comment by dinbtechit** [comment]
Thanks for the help. I did not know that there was `zmq-sys` that seems to get back the initial error. Now I got another. There is a workaround for this in the readme file. But I cannot follow what the solution is. Are you able to help?

```
 note: /usr/bin/ld: /app/target/release/deps/libsqlx_macros-2a5b0af84def8796.so: no symbol version section for versioned symbol `fcntl@GLIBC_2.2.5'
          collect2: error: ld returned 1 exit status

```

**Comment by messense** [comment]
It's a bit odd that the error is coming from `ld` instead of `zig`/`lld`, so I'm not sure.

`libsqlx_macros` looks like a proc-macro crate that should be compiled for the build/host machine, what's your OS, CPU architecture and rustc version?

**Comment by dinbtechit** [comment]
I'm running in a docker. Here are the details.

OS - Docker Ubuntu 22.04 (aarm64 CPU) (host machine M1 Mac aarch64 )
rust version

```
Default host: aarch64-unknown-linux-gnu
rustup home:  /root/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-aarch64-unknown-linux-gnu (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-aarch64-unknown-linux-gnu (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

**Comment by messense** [comment]
Docker isn't required for `cargo-zigbuild`, can you try run it directly on macOS? Cargo has some oddities when `--target` is the same as the build/host target namely https://github.com/rust-lang/cargo/issues/3349.

**Comment by messense** [comment]
Maybe you should switch to https://github.com/jedisct1/libsodium-sys-stable, `libsodium-sys` is unmaintained.

**Comment by dinbtechit** [comment]
Yeah I tried that as well. Nothing seems to work.  Looks like I can't use zigbuild for this specific project.  

`cargo build` works if I statistically link the libraries. The only problem is I can't cross-compile.

 I really appreciate all your answers.

**Comment by messense** [comment]
`libsodium-sys-stable` works for me.

```bash
$ cargo new hello
     Created binary (application) `hello` package
$ cargo add libsodium-sys-stable
    Updating crates.io index
      Adding libsodium-sys-stable v1.19.27 to dependencies.
             Features:
             - fetch-latest
             - minimal
             - optimized
             - ureq
             - use-pkg-config
$ cat src/main.rs
use libsodium_sys::*;

fn main() {
    assert_eq!(
        unsafe { crypto_verify_16_bytes() },
        crypto_verify_16_BYTES as usize
    );
}
$ cargo zigbuild --target aarch64-unknown-linux-gnu -vv
       Fresh cfg-if v1.0.0
       Fresh rle-decode-fast v1.0.3
       Fresh adler32 v1.2.0
       Fresh minisign-verify v0.2.1
       Fresh cc v1.0.79
       Fresh libflate_lz77 v1.1.0
       Fresh pkg-config v0.3.26
   Compiling libc v0.2.139
       Fresh xattr v0.2.3
       Fresh filetime v0.2.20
       Fresh crc32fast v1.3.2
     Running `/private/tmp/hello/target/debug/build/libc-da11048515868f5e/build-script-build`
       Fresh tar v0.4.38
       Fresh libflate v1.2.0
   Compiling libsodium-sys-stable v1.19.27
     Running `/private/tmp/hello/target/debug/build/libsodium-sys-stable-a86757b1bb28c9d6/build-script-build`
[libc 0.2.139] cargo:rerun-if-changed=build.rs
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=SODIUM_LIB_DIR
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=SODIUM_SHARED
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=SODIUM_USE_PKG_CONFIG
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=SODIUM_DISABLE_PIE
[libc 0.2.139] cargo:rustc-cfg=freebsd11
[libc 0.2.139] cargo:rustc-cfg=libc_priv_mod_use
[libc 0.2.139] cargo:rustc-cfg=libc_union
[libc 0.2.139] cargo:rustc-cfg=libc_const_size_of
[libc 0.2.139] cargo:rustc-cfg=libc_align
[libc 0.2.139] cargo:rustc-cfg=libc_int128
[libc 0.2.139] cargo:rustc-cfg=libc_core_cvoid
[libc 0.2.139] cargo:rustc-cfg=libc_packedN
[libc 0.2.139] cargo:rustc-cfg=libc_cfg_target_vendor
[libc 0.2.139] cargo:rustc-cfg=libc_non_exhaustive
[libc 0.2.139] cargo:rustc-cfg=libc_ptr_addr_of
[libc 0.2.139] cargo:rustc-cfg=libc_underscore_const_names
[libc 0.2.139] cargo:rustc-cfg=libc_const_extern_fn
     Running `CARGO=/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo CARGO_CRATE_NAME=libc CARGO_MANIFEST_DIR=/Users/messense/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139 CARGO_PKG_AUTHORS='The Rust Project Developers' CARGO_PKG_DESCRIPTION='Raw FFI bindings to platform libraries like libc.
' CARGO_PKG_HOMEPAGE='https://github.com/rust-lang/libc' CARGO_PKG_LICENSE='MIT OR Apache-2.0' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=libc CARGO_PKG_REPOSITORY='https://github.com/rust-lang/libc' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.2.139 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=2 CARGO_PKG_VERSION_PATCH=139 CARGO_PKG_VERSION_PRE='' DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/hello/target/debug/deps:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/lib:/usr/local/lib:/usr/lib' OUT_DIR=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libc-64e84bd569a491f1/out rustc --crate-name libc /Users/messense/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f8dfbc19102eb84d -C extra-filename=-f8dfbc19102eb84d --out-dir /private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-unknown-linux-gnu-gcc -L dependency=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/private/tmp/hello/target/debug/deps --cap-lints warn --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_int128 --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor --cfg libc_non_exhaustive --cfg libc_ptr_addr_of --cfg libc_underscore_const_names --cfg libc_const_extern_fn`
[libsodium-sys-stable 1.19.27] OPT_LEVEL = Some("0")
[libsodium-sys-stable 1.19.27] TARGET = Some("aarch64-unknown-linux-gnu")
[libsodium-sys-stable 1.19.27] HOST = Some("aarch64-apple-darwin")
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
[libsodium-sys-stable 1.19.27] CC_aarch64-unknown-linux-gnu = None
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
[libsodium-sys-stable 1.19.27] CC_aarch64_unknown_linux_gnu = Some("aarch64-unknown-linux-gnu-gcc")
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
[libsodium-sys-stable 1.19.27] CFLAGS_aarch64-unknown-linux-gnu = None
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
[libsodium-sys-stable 1.19.27] CFLAGS_aarch64_unknown_linux_gnu = None
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=TARGET_CFLAGS
[libsodium-sys-stable 1.19.27] TARGET_CFLAGS = None
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CFLAGS
[libsodium-sys-stable 1.19.27] CFLAGS = None
[libsodium-sys-stable 1.19.27] cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
[libsodium-sys-stable 1.19.27] CRATE_CC_NO_DEFAULTS = None
[libsodium-sys-stable 1.19.27] DEBUG = Some("true")
[libsodium-sys-stable 1.19.27] CARGO_CFG_TARGET_FEATURE = Some("neon")
[libsodium-sys-stable 1.19.27] cargo:rustc-link-lib=static=sodium
[libsodium-sys-stable 1.19.27] cargo:rustc-link-search=native=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out/installed/lib
[libsodium-sys-stable 1.19.27] cargo:include=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out/source/libsodium-stable/src/libsodium/include
[libsodium-sys-stable 1.19.27] cargo:lib=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out/installed/lib
     Running `CARGO=/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo CARGO_CRATE_NAME=libsodium_sys CARGO_MANIFEST_DIR=/Users/messense/.cargo/registry/src/github.com-1ecc6299db9ec823/libsodium-sys-stable-1.19.27 CARGO_PKG_AUTHORS='dnaq:jedisct1' CARGO_PKG_DESCRIPTION='Maintained FFI bindings for libsodium stable' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='MIT OR Apache-2.0' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=libsodium-sys-stable CARGO_PKG_REPOSITORY='https://github.com/jedisct1/libsodium-sys-stable' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=1.19.27 CARGO_PKG_VERSION_MAJOR=1 CARGO_PKG_VERSION_MINOR=19 CARGO_PKG_VERSION_PATCH=27 CARGO_PKG_VERSION_PRE='' DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/hello/target/debug/deps:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/lib:/usr/local/lib:/usr/lib' OUT_DIR=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out rustc --crate-name libsodium_sys /Users/messense/.cargo/registry/src/github.com-1ecc6299db9ec823/libsodium-sys-stable-1.19.27/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=82ec504b9e478e9d -C extra-filename=-82ec504b9e478e9d --out-dir /private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-unknown-linux-gnu-gcc -L dependency=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/private/tmp/hello/target/debug/deps --extern libc=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps/liblibc-f8dfbc19102eb84d.rmeta --cap-lints warn -L native=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out/installed/lib -l static=sodium`
   Compiling hello v0.1.0 (/private/tmp/hello)
     Running `CARGO=/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo CARGO_BIN_NAME=hello CARGO_CRATE_NAME=hello CARGO_MANIFEST_DIR=/private/tmp/hello CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=hello CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 DYLD_FALLBACK_LIBRARY_PATH='/private/tmp/hello/target/debug/deps:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/messense/lib:/usr/local/lib:/usr/lib' rustc --crate-name hello --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1654636f1b3efdd7 -C extra-filename=-1654636f1b3efdd7 --out-dir /private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-unknown-linux-gnu-gcc -C incremental=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/incremental -L dependency=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/private/tmp/hello/target/debug/deps --extern libsodium_sys=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/deps/liblibsodium_sys-82ec504b9e478e9d.rlib -L native=/private/tmp/hello/target/aarch64-unknown-linux-gnu/debug/build/libsodium-sys-stable-89142f0be5ca3d78/out/installed/lib`
    Finished dev [unoptimized + debuginfo] target(s) in 9.13s
```

Make sure you didn't enable the `use-pkg-config` feature by accident.

**Comment by dinbtechit** [comment]
Let me check on the `use-pkg-config`.. Can you try `libsodium-sys = "0.0.16"`. Unfortunately, that is the version I am stuck with. Looks like one of my underlying crates is using that specific version.

**Comment by messense** [comment]
> Can you try `libsodium-sys = "0.0.16"`

https://github.com/sodiumoxide/sodiumoxide/blob/31fab63e0910176ddc74a04aec315b7bf12685ce/libsodium-sys/build.rs#L8-L20

It requires `pkg-config` or a pre-compiled static/shared lib, so it's not going to work.

**Comment by dinbtechit** [comment]
Ahh ok, that makes sense! Thank you so much for all the help. I massively appreciate that. 🙏🙏🙏
